
image: debian:stable

before_script:
  - apt-get update -qq && apt-get install -y -qq
  - apt-get install -y -qq make
  - apt-get install -y -qq libfftw3-dev libblas-dev libpng-dev
  - apt-get install -y -qq gcc liblapacke-dev

stages:
  - build
  - test1
  - test2

Build:
  stage: build
  script:
    - make

Unit_Test:
  stage: test1
  script:
    - make utest

Integration_Test:
  stage: test2
  script:
    - make test


